name = "ayudame"
compatibility_date = "2024-08-15"

[site]
bucket = "./"

[[builds]]
command = ""
upload_dir = "./"

[env.production]
name = "ayudame-production"

# Custom domain configuration will be handled in Cloudflare dashboard
# Domain: ayudame.com.do